[colors]
background = #000000
foreground = #cccccc
color0 = #282C34
color1 = #e06c75
color2 = #99c47a
color3 = #e3be79
color4 = #5dabeb
color5 = #c678dd
color6 = #56b6c2
color7 = #abb2bf
color8 = #222222
color9 = #e06c75
color10 = #99c47a
color11 = #e3be79
color12 = #5dabeb
color13 = #c678dd
color14 = #56b6c2
color15 = #abb2bf
dark-light = #222222
active-light = #777777

[bar/pdillo-polybar]
width =  100%
height = 25
padding-left = 1
padding-right = 1
background = ${colors.background}
foreground = ${colors.foreground}
bottom = false
border-top-size = 7
border-bottom-size = 7
border-top-color = ${colors.background}
border-bottom-color = ${colors.background}
line-size = 1
monitor = eDP-1
enable-ipc = true

modules-left = menu-apps spaces round-left i3 round-right pipe polywins
modules-center = round-left time round-right
modules-right =  round-left root cpu temperature round-right spaces round-left pulseaudio backlight round-right spaces round-left battery round-right tray

font-0 = JetBrainsMono Nerd Font:style=Bold:pixelsize=12;3
font-1 = JetBrainsMono Nerd Font:size=18;3
font-2 = Material Icons:style=Bold:size=19;3
font-3 = unifont:fontformat=truetype:size=14:antialias=true;
font-4 = Symbola:size=9;
font-5 = JetBrainsMono Nerd Font:style=Regular:pixelsize=12;3

[bar/pdillo-polybar/module/i3]
inherit = module/i3
output = eDP-1

[bar/external-polybar]
width = 100%
height = 25
padding-left = 1
padding-right = 1
background = ${colors.background}
foreground = ${colors.foreground}
bottom = false
border-top-size = 7
border-bottom-size = 7
border-top-color = ${colors.background}
border-bottom-color = ${colors.background}
line-size = 1
monitor = HDMI-2
enable-ipc = true

modules-left = menu-apps spaces round-left i3 round-right pipe polywins
modules-center = round-left time round-right
modules-right =  round-left root cpu temperature round-right spaces round-left pulseaudio backlight round-right spaces round-left battery round-right tray

font-0 = JetBrainsMono Nerd Font:style=Bold:pixelsize=12;3
font-1 = JetBrainsMono Nerd Font:size=18;3
font-2 = Material Icons:style=Bold:size=19;3
font-3 = unifont:fontformat=truetype:size=14:antialias=true;
font-4 = Symbola:size=9;
font-5 = JetBrainsMono Nerd Font:style=Regular:pixelsize=12;3

[bar/external-polybar/module/i3]
inherit = module/i3
output = HDMI-2

[module/pipe]
type = custom/text
label = %{T3} | %{T-}
label-foreground = ${colors.color8}

[module/spaces]
type = custom/text
label = %{T3} %{T-}

[module/round-left]
type = custom/text
label = %{T2}%{T-}
label-foreground = ${colors.color8}

[module/round-right]
type = custom/text
label = %{T2}%{T-}
label-foreground = ${colors.color8}

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 65
format = <label>
format-prefix = 󰔏 
format-prefix-padding = 2px
format-prefix-foreground = ${colors.active-light}
format-warn = <ramp>  <label-warn>
format-background = ${colors.color8}
label = %temperature-f%
label-warn = %temperature-f%
label-warn-backgroud = #b48ead
format-padding = 1
ramp-0 = 󰔏
ramp-foreground = ${colors.active-light}

[module/root]
type = custom/script
exec = df -h | head -n 5 | tail -n 1 | cut -d 'G' -f4 | cut -d'/' -f1 | tr -d ' '
format = <label>
format-prefix = 󰋊
format-prefix-padding = 1
format-prefix-foreground = ${colors.active-light}
label = %output%
format-padding = 3px
format-background = ${colors.color8}

[module/i3]
type = internal/i3

pin-workspaces = false
show-urgent = true
fuzzy-match = true

format = <label-state>

ws-icon-0 =1;1
ws-icon-1 =2;2
ws-icon-2 =3;3
ws-icon-3 =4;4
ws-icon-4 =5;5
ws-icon-5 =6;6
ws-icon-6 =7;7
ws-icon-7 =8;8
ws-icon-8 =9;9
ws-icon-9 =10;10

ws-icon-default = *;*

label-focused = %icon%
label-focused-underline = ${colors.color1}
label-focused-padding = 1
label-focused-background = ${colors.color8}

label-unfocused = %icon%
label-unfocused-background = ${colors.color8}
label-unfocused-padding = 1
label-unfocused-foreground = ${colors.active-light}

label-occupied = %icon%
label-occupied-padding = 1
label-occupied-background = ${colors.color8}

label-empty = %icon%
label-empty-padding = 1
label-empty-background = ${colors.color8}

label-urgent = %icon%
label-urgent-foreground = #88C0D0
label-urgent-padding = 1
label-urgent-background = ${colors.color8}

[module/polywins]
type = custom/script
exec = ~/.config/polybar/scripts/polywins.sh 2>/dev/null
format = <label>
label = %output%
tail = true

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <ramp-volume><label-volume>
label-volume = %percentage%%
format-volume-background = ${colors.color8}
format-volume-padding = 1
ramp-volume-0 = "󰕿 "
ramp-volume-1 = "󰖀 "
ramp-volume-2 = "󰕾 "
ramp-volume-foreground = ${colors.active-light}
label-muted = "󰖁 "
label-muted-foreground = ${colors.active-light}
label-muted-background = ${colors.color8}

[module/time]
type = internal/date
interval = 60
format = <label>
format-background = ${colors.dark-light}
label-padding-right = 1
date = %{F#777777}󰥔 %{F-}%{F#cccccc}%I:%M%{F-}
time-alt = %{F#777777}󰃮 %{F-}%{F#cccccc}%a, %b %d%{F-}
label-background = ${colors.color8}
label = %date%%time%

[module/backlight]
type = internal/backlight
card = intel_backlight
format = <ramp><label>
ramp-foreground = ${colors.active-light}
format-background = ${colors.color8}
label = %percentage%%
format-padding = 1

ramp-0 = "󰃞 "
ramp-1 = "󰃟 "
ramp-2 = "󰃝 "
ramp-3 = "󰃠 "

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-background = ${colors.color8}
format-charging-padding = 1
label-charging = %percentage%%
animation-charging-foreground = ${colors.active-light}

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = ${colors.color8}
format-discharging-padding = 1
label-discharging = %percentage%%
ramp-capacity-foreground = ${colors.active-light}

format-full-prefix = "󰁹 "
format-full-prefix-foreground = ${colors.active-light}
format-full-background = ${colors.color8}
format-full-padding = 1

ramp-capacity-0 = 󰁺
ramp-capacity-1 = 󰁼
ramp-capacity-2 = 󰁾
ramp-capacity-3 = 󰂁
ramp-capacity-4 = 󰁹

animation-charging-0 = 󰁺
animation-charging-1 = 󰁼
animation-charging-2 = 󰁾
animation-charging-3 = 󰂁
animation-charging-4 = 󰁹
animation-charging-framerate = 750

[module/cpu]
type = internal/cpu
interval = 2.5
format = <label>
format-prefix = 󰘚 
format-prefix-padding = 1
;format-prefix = CPU:
format-prefix-foreground = ${colors.active-light}
label = %percentage%%
format-background = ${colors.color8}
format-padding = 3px

[module/sysmenu]
type = custom/text
content = 
content-foreground = ${colors.active-light}
content-padding = 1
click-left = ~/.config/polybar/scripts/powermenu.sh

[module/menu-apps]
type = custom/menu

menu-0-0 = Lock
menu-0-0-padding = 1
menu-0-0-exec = betterlockscreen -l
menu-0-1 = Reboot
menu-0-1-padding = 1
menu-0-1-exec = loginctl reboot
menu-0-2 = Shutdown
menu-0-2-padding = 1
menu-0-2-exec = loginctl shutdown

label-open = 
label-open-foreground = ${colors.active-light}
label-open-padding = 1
label-close = 󰅖
label-close-foreground = ${colors.color1}
label-close-padding = 1

label-separator = |
label-separator-foreground = ${colors.dark-light}

[module/tray]
type = internal/tray
tray-padding = 12px
